### PR TITLE
postgres: Upsert legacy `json` columns (fixes #85)

### LINKED ISSUE #85: can't upsert into postgres table with legacy json columns
you will get a

```
db error: ERROR: unsupported jsonb version number 123
```

### PR DESCRIPTION
**Pull request by emk**
The key trick here is that we need to fetch any existing schema _before_
calling `prepare_table`. This whole system needs to be re-designed as
part of the "shortcuts" system some day. We also need to inspect a
number of other functions in other drivers for similar problems. Again,
there's a missing abstraction here.

To make this work, we encapsulated the pg_catalog reading logic and
forced all callers to go through the same API. We also fixed an issue
where catalog lookups were being done synchronously inside async code.

### CODE REVIEW

File: dbcrossbarlib/src/drivers/postgres_shared/table.rs [hunk 1]
```diff
@@ -7,6 +7,27 @@ use crate::common::*;
...
+    /// Check the PostgreSQL catalog for an existing schema.
+    Yes,
+    /// Always use the schema given by the user.
+    No,
+}
+
+impl From<&IfExists> for CheckCatalog {
+    fn from(if_exists: &IfExists) -> CheckCatalog {
+        match if_exists {
+            IfExists::Error | IfExists::Overwrite => CheckCatalog::No,
```
Comment (seamusabshere) [inline dbcrossbarlib/src/drivers/postgres_shared/table.rs]: hmm but... isn't it useful to pre-check the catalog in _any_ mode, since you might learn things that help you transform cols?

Comment (emk) [reply dbcrossbarlib/src/drivers/postgres_shared/table.rs]: @seamusabshere In `--overwrite` mode, we want to ignore any pre-existing schema, because it might have totally different columns. So we don't even look at the existing destination table; we just delete it.
