### PR TITLE
Assorted `dbcrossbar` fixes (fixes #84, #101, #104)

### LINKED ISSUE #84: cp fails on bigquery to postgres for column names with capital letters
I got this error on mac with release `v0.2.8`.

I have a table in bigquery where columns have capital letters, such as `Col_Name`. When I ran `./dbcrossbar cp --temporary=gs:/my-bucket/ bigquery:bq-project:dataset.table 'postgres://postgres:@localhost:5432/db#table'` I encountered the following error:

`Error: CSV file has column col_name at position 1, but schema has Col_Name`

It looks like dbcrossbar selects the columns in BigQuery via the lowercase names. This causes the csv files to have a lowercase header, which does not match up with the schema generated by dbcrossbar for postgres.

### PR DESCRIPTION
**Pull request by emk**
This PR fixes a number of issues, and you'll want to review the patches individually (and not all as a single diff):

- BigQuery: NULL boolean fixes.
- BigML: Faster failure if no S3 bucket specified.
- PostgreSQL and BigQuery: Better handling of mixed-case columns.

The third includes a breaking policy change: `dbcrossbar` will no longer edit your column names under any circumstances. It's now your job to make sure that all column names are valid according to the destination database, and we will error out if you aren't. If you're using `scrubcsv --clean-column-names` at your perimeter, this should not break importing data. But if you have mixed-case columns in BigQuery and PostgreSQL, and you copy them back and forth, you may need to ensure that both databases agree on the cases of column names.

### CODE REVIEW

File: dbcrossbarlib/src/drivers/bigquery_shared/column_name.rs [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+
+impl ColumnName {
+    /// The original string, including case information.
+    pub(crate) fn as_str(&self) -> &str {
+        &self.data[..self.data.len() / 2]
+    }
+
+    /// Am all-lowecase version
+    fn as_lowercase(&self) -> &str {
+        &self.data[self.data.len() / 2..]
```
Comment (seamusabshere) [inline dbcrossbarlib/src/drivers/bigquery_shared/column_name.rs]: wow that does not look like "make me lowercase"

Comment (emk) [reply dbcrossbarlib/src/drivers/bigquery_shared/column_name.rs]: Did you see the comment on the `data` member? We pre-compute the lowercase string and append it to the regular string, and then use either the first or second half of the buffer via `as_str` or `as_lowercase`.
